services:
    laravel.test:
        build:
            context: "."
            dockerfile: ./docker/8.4/Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: "sail-8.4/app"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-443}:443"
            - "${APP_PORT:-443}:443/udp"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
            - "8443:443"
            - "8443:443/udp"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
            SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=frankenphp --host=localhost --admin-port=2019 --port=443 --https --watch"
            XDG_CONFIG_HOME: /var/www/html/config
            XDG_DATA_HOME: /var/www/html/data
        volumes:
            - ".:/var/www/html"
            - "./data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/frankenphp-root.crt"
            - "./docker/8.4/php.ini:/etc/php/8.4/cli/conf.d/99-sail.ini"
        networks:
            - sail
        depends_on:
            - mysql
            - valkey
            - mailpit
    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "sail-mysql:/var/lib/mysql"
            - "./docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s
    valkey:
        image: "valkey/valkey:alpine"
        ports:
            - "${FORWARD_VALKEY_PORT:-6379}:6379"
        volumes:
            - "sail-valkey:/data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - valkey-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-valkey:
        driver: local
